// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxzZ4xqYywLFczryzoJ5zugh3vkolWZ0',
    appId: '1:682284846181:web:19b36cf745b7ad0edc0a8c',
    messagingSenderId: '682284846181',
    projectId: 'tools-for-various-games',
    authDomain: 'tools-for-various-games.firebaseapp.com',
    storageBucket: 'tools-for-various-games.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoXaXi5FXu1-pGp-Kvc8QkRlmAvQcMG4',
    appId: '1:682284846181:android:5048660477cd738ddc0a8c',
    messagingSenderId: '682284846181',
    projectId: 'tools-for-various-games',
    storageBucket: 'tools-for-various-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbdbhORD9tnT2DK5NEm20mQzzDVrVdLk',
    appId: '1:682284846181:ios:ebe764338ca39d55dc0a8c',
    messagingSenderId: '682284846181',
    projectId: 'tools-for-various-games',
    storageBucket: 'tools-for-various-games.appspot.com',
    iosClientId: '682284846181-69trore52fiapo9eilce635275ah34nj.apps.googleusercontent.com',
    iosBundleId: 'com.patryklaskowski.instrumentsForVariousGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbdbhORD9tnT2DK5NEm20mQzzDVrVdLk',
    appId: '1:682284846181:ios:ebe764338ca39d55dc0a8c',
    messagingSenderId: '682284846181',
    projectId: 'tools-for-various-games',
    storageBucket: 'tools-for-various-games.appspot.com',
    iosClientId: '682284846181-69trore52fiapo9eilce635275ah34nj.apps.googleusercontent.com',
    iosBundleId: 'com.patryklaskowski.instrumentsForVariousGames',
  );
}
